replicaCount: 1

image:
  repository: 767224848485.dkr.ecr.ap-south-1.amazonaws.com/testrepo
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: your-app.example.com
      paths:
        - path: /
          pathType: Prefix
